// <auto-generated />
using System;
using GymTrackPro.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTrackPro.API.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260711204834_StageFirebaseIdentityAndAccountInvites")]
    partial class StageFirebaseIdentityAndAccountInvites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymTrackPro.Shared.Entities.AccountInvite", b =>
                {
                    b.Property<int>("AccountInviteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountInviteID"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntendedRole")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("RedemptionOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("TargetMemberID")
                        .HasColumnType("int");

                    b.Property<int?>("TargetUserID")
                        .HasColumnType("int");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .IsFixedLength();

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsedByFirebaseUid")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("AccountInviteID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("IX_AccountInvites_NormalizedEmail");

                    b.HasIndex("RedemptionOperationId")
                        .IsUnique()
                        .HasDatabaseName("UX_AccountInvites_RedemptionOperationId")
                        .HasFilter("[RedemptionOperationId] IS NOT NULL");

                    b.HasIndex("TargetMemberID");

                    b.HasIndex("TargetUserID");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_AccountInvites_TokenHash");

                    b.ToTable("AccountInvites", null, t =>
                        {
                            t.HasCheckConstraint("CK_AccountInvites_ExactlyOneTarget", "([TargetMemberID] IS NOT NULL AND [TargetUserID] IS NULL) OR ([TargetMemberID] IS NULL AND [TargetUserID] IS NOT NULL)");

                            t.HasCheckConstraint("CK_AccountInvites_ExpiryAfterCreation", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_AccountInvites_NormalizedEmailNotBlank", "LEN([NormalizedEmail]) > 0");

                            t.HasCheckConstraint("CK_AccountInvites_PurposeNotBlank", "LEN(LTRIM(RTRIM([Purpose]))) > 0");

                            t.HasCheckConstraint("CK_AccountInvites_RevokedTimestampAfterCreation", "[RevokedAtUtc] IS NULL OR [RevokedAtUtc] >= [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_AccountInvites_TargetRole", "([TargetMemberID] IS NOT NULL AND [IntendedRole] = 2) OR ([TargetUserID] IS NOT NULL AND [IntendedRole] IN (0, 1))");

                            t.HasCheckConstraint("CK_AccountInvites_RedemptionMetadata", "([UsedAtUtc] IS NULL AND [UsedByFirebaseUid] IS NULL AND [RedemptionOperationId] IS NULL) OR ([UsedAtUtc] IS NOT NULL AND [UsedByFirebaseUid] IS NOT NULL AND [RedemptionOperationId] IS NOT NULL AND [RedemptionOperationId] <> CAST('00000000-0000-0000-0000-000000000000' AS uniqueidentifier))");

                            t.HasCheckConstraint("CK_AccountInvites_UsedOrRevoked", "[UsedAtUtc] IS NULL OR [RevokedAtUtc] IS NULL");

                            t.HasCheckConstraint("CK_AccountInvites_UsedBeforeExpiry", "[UsedAtUtc] IS NULL OR [UsedAtUtc] < [ExpiresAtUtc]");

                            t.HasCheckConstraint("CK_AccountInvites_UsedTimestampAfterCreation", "[UsedAtUtc] IS NULL OR [UsedAtUtc] >= [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_AccountInvites_UsedUidNotBlank", "[UsedByFirebaseUid] IS NULL OR LEN([UsedByFirebaseUid]) > 0");
                        });
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Attendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceID"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.HasKey("AttendanceID");

                    b.HasIndex("MemberID");

                    b.ToTable("AttendanceLogs");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MemberID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("QRCode")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.MemberProjectionVersion", b =>
                {
                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("MemberID");

                    b.ToTable("MemberProjectionVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_MemberProjectionVersions_VersionRange", "[Version] >= 0 AND [Version] <= 2199023255551");
                        });
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.MembershipPause", b =>
                {
                    b.Property<int>("PauseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PauseID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PauseEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PauseStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SubscriptionID")
                        .HasColumnType("int");

                    b.HasKey("PauseID");

                    b.HasIndex("SubscriptionID");

                    b.ToTable("MembershipPauses");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.MembershipPlan", b =>
                {
                    b.Property<int>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PlanID");

                    b.HasIndex("PlanName")
                        .IsUnique();

                    b.ToTable("MembershipPlans");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NotificationID");

                    b.HasIndex("MemberID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatePaid")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SubscriptionID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("MemberID");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.HasIndex("SubscriptionID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Subscription", b =>
                {
                    b.Property<int>("SubscriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("PlanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SubscriptionID");

                    b.HasIndex("MemberID");

                    b.HasIndex("PlanID");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.SystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettingKey");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            SettingKey = "GymName",
                            Description = "Name of the gym facility.",
                            GroupName = "General",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "GymTrackPro"
                        },
                        new
                        {
                            SettingKey = "ContactNumber",
                            Description = "Gym contact helpline phone number.",
                            GroupName = "General",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "+639170000000"
                        },
                        new
                        {
                            SettingKey = "Currency",
                            Description = "Currency code used for financial billing transactions.",
                            GroupName = "General",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "PHP"
                        },
                        new
                        {
                            SettingKey = "Timezone",
                            Description = "System local timezone identifier.",
                            GroupName = "General",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "Asia/Manila"
                        },
                        new
                        {
                            SettingKey = "QRPrefix",
                            Description = "Format prefix added to automatically generated member QR codes.",
                            GroupName = "Membership",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "GTP-"
                        },
                        new
                        {
                            SettingKey = "ReceiptPrefix",
                            Description = "Format prefix added to payment invoice transaction receipts.",
                            GroupName = "Payments",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "REC-"
                        },
                        new
                        {
                            SettingKey = "MaxUploadSize",
                            Description = "Maximum member photo upload limit size in bytes (e.g. 5MB = 5242880).",
                            GroupName = "Security",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "5242880"
                        },
                        new
                        {
                            SettingKey = "AllowedImageTypes",
                            Description = "Comma-separated list of approved image file extensions.",
                            GroupName = "Security",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = ".jpg,.jpeg,.png"
                        },
                        new
                        {
                            SettingKey = "PasswordPolicyRegex",
                            Description = "Regex pattern validating password strength rules.",
                            GroupName = "Security",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$"
                        },
                        new
                        {
                            SettingKey = "ReminderDaysBeforeExpiration",
                            Description = "Days ahead of membership expiration to raise alerts or send reminders.",
                            GroupName = "Membership",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "3"
                        },
                        new
                        {
                            SettingKey = "StaleSessionHours",
                            Description = "Hours after which an open attendance session is considered stale.",
                            GroupName = "Attendance",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "16"
                        });
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FirebaseUid")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MemberID")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirebaseUid")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_FirebaseUid")
                        .HasFilter("[FirebaseUid] IS NOT NULL");

                    b.HasIndex("MemberID")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_MemberID")
                        .HasFilter("[MemberID] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedEmail")
                        .HasFilter("[NormalizedEmail] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_FirebaseUidNotBlank", "[FirebaseUid] IS NULL OR LEN([FirebaseUid]) > 0");

                            t.HasCheckConstraint("CK_Users_NormalizedEmailNotBlank", "[NormalizedEmail] IS NULL OR LEN([NormalizedEmail]) > 0");

                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_Users_RoleMemberLink", "([Role] = 2 AND [MemberID] IS NOT NULL) OR ([Role] IN (0, 1) AND [MemberID] IS NULL)");
                        });
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.WalkInVisitor", b =>
                {
                    b.Property<int>("VisitorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorID"));

                    b.Property<decimal>("FeePaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Purpose")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VisitorID");

                    b.ToTable("WalkInVisitors");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.AccountInvite", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymTrackPro.Shared.Entities.Member", "TargetMember")
                        .WithMany()
                        .HasForeignKey("TargetMemberID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GymTrackPro.Shared.Entities.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("TargetMember");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.MemberProjectionVersion", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.Member", "Member")
                        .WithOne()
                        .HasForeignKey("GymTrackPro.Shared.Entities.MemberProjectionVersion", "MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Attendance", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.AuditLog", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.MembershipPause", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Notification", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Payment", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymTrackPro.Shared.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Subscription", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTrackPro.Shared.Entities.MembershipPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.User", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.Member", "Member")
                        .WithOne()
                        .HasForeignKey("GymTrackPro.Shared.Entities.User", "MemberID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
