// <auto-generated />
using System;
using GymTrackPro.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTrackPro.API.Migrations
{
    [DbContext(typeof(GymDbContext))]
    partial class GymDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymTrackPro.Shared.Entities.AccountInvite", b =>
                {
                    b.Property<int>("AccountInviteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountInviteID"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntendedRole")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("RedemptionOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("TargetMemberID")
                        .HasColumnType("int");

                    b.Property<int?>("TargetUserID")
                        .HasColumnType("int");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsedByFirebaseUid")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("AccountInviteID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("TargetMemberID");

                    b.HasIndex("TargetUserID");

                    b.ToTable("AccountInvites");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Attendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceID"));

                    b.Property<int?>("ActorUserID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Source")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("SupersededByAttendanceID")
                        .HasColumnType("int");

                    b.Property<int?>("VoidActorUserID")
                        .HasColumnType("int");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("AttendanceID");

                    b.HasIndex("ActorUserID");

                    b.HasIndex("MemberID");

                    b.HasIndex("SupersededByAttendanceID");

                    b.HasIndex("VoidActorUserID");

                    b.ToTable("AttendanceLogs");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.AttendanceAdjustment", b =>
                {
                    b.Property<long>("AttendanceAdjustmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttendanceAdjustmentID"));

                    b.Property<int>("ActorUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AfterCheckOutTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("AfterIsVoided")
                        .HasColumnType("bit");

                    b.Property<int?>("AfterSupersededByAttendanceID")
                        .HasColumnType("int");

                    b.Property<int>("AttendanceID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BeforeCheckOutTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("BeforeIsVoided")
                        .HasColumnType("bit");

                    b.Property<int?>("BeforeSupersededByAttendanceID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid>("OperationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AttendanceAdjustmentID");

                    b.HasIndex("ActorUserID");

                    b.HasIndex("AttendanceID");

                    b.HasIndex("OperationID")
                        .IsUnique();

                    b.ToTable("AttendanceAdjustments");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.AttendanceOperation", b =>
                {
                    b.Property<Guid>("OperationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActorUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<int>("OriginalHttpStatus")
                        .HasColumnType("int");

                    b.Property<string>("OriginalResultCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int?>("TargetAttendanceID")
                        .HasColumnType("int");

                    b.HasKey("OperationID");

                    b.HasIndex("ActorUserID");

                    b.HasIndex("TargetAttendanceID");

                    b.ToTable("AttendanceOperations");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MemberID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("QRCode")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.MemberProjectionVersion", b =>
                {
                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("MemberID");

                    b.ToTable("MemberProjectionVersions");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.MembershipPause", b =>
                {
                    b.Property<int>("PauseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PauseID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PauseEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PauseStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SubscriptionID")
                        .HasColumnType("int");

                    b.HasKey("PauseID");

                    b.HasIndex("SubscriptionID");

                    b.ToTable("MembershipPauses");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.MembershipPlan", b =>
                {
                    b.Property<int>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PlanID");

                    b.HasIndex("PlanName")
                        .IsUnique();

                    b.ToTable("MembershipPlans");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NotificationID");

                    b.HasIndex("MemberID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatePaid")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SubscriptionID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("MemberID");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.HasIndex("SubscriptionID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Subscription", b =>
                {
                    b.Property<int>("SubscriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("PlanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SubscriptionID");

                    b.HasIndex("MemberID");

                    b.HasIndex("PlanID");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.SystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettingKey");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            SettingKey = "GymName",
                            Description = "Name of the gym facility.",
                            GroupName = "General",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "GymTrackPro"
                        },
                        new
                        {
                            SettingKey = "ContactNumber",
                            Description = "Gym contact helpline phone number.",
                            GroupName = "General",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "+639170000000"
                        },
                        new
                        {
                            SettingKey = "Currency",
                            Description = "Currency code used for financial billing transactions.",
                            GroupName = "General",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "PHP"
                        },
                        new
                        {
                            SettingKey = "Timezone",
                            Description = "System local timezone identifier.",
                            GroupName = "General",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "Asia/Manila"
                        },
                        new
                        {
                            SettingKey = "QRPrefix",
                            Description = "Format prefix added to automatically generated member QR codes.",
                            GroupName = "Membership",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "GTP-"
                        },
                        new
                        {
                            SettingKey = "ReceiptPrefix",
                            Description = "Format prefix added to payment invoice transaction receipts.",
                            GroupName = "Payments",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "REC-"
                        },
                        new
                        {
                            SettingKey = "MaxUploadSize",
                            Description = "Maximum member photo upload limit size in bytes (e.g. 5MB = 5242880).",
                            GroupName = "Security",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "5242880"
                        },
                        new
                        {
                            SettingKey = "AllowedImageTypes",
                            Description = "Comma-separated list of approved image file extensions.",
                            GroupName = "Security",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = ".jpg,.jpeg,.png"
                        },
                        new
                        {
                            SettingKey = "PasswordPolicyRegex",
                            Description = "Regex pattern validating password strength rules.",
                            GroupName = "Security",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$"
                        },
                        new
                        {
                            SettingKey = "ReminderDaysBeforeExpiration",
                            Description = "Days ahead of membership expiration to raise alerts or send reminders.",
                            GroupName = "Membership",
                            LastModified = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "3"
                        });
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FirebaseUid")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MemberID")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MemberID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.WalkInVisitor", b =>
                {
                    b.Property<int>("VisitorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorID"));

                    b.Property<decimal>("FeePaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Purpose")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VisitorID");

                    b.ToTable("WalkInVisitors");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.AccountInvite", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymTrackPro.Shared.Entities.Member", "TargetMember")
                        .WithMany()
                        .HasForeignKey("TargetMemberID");

                    b.HasOne("GymTrackPro.Shared.Entities.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserID");

                    b.Navigation("CreatedByUser");

                    b.Navigation("TargetMember");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Attendance", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserID");

                    b.HasOne("GymTrackPro.Shared.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTrackPro.Shared.Entities.Attendance", "SupersededByAttendance")
                        .WithMany()
                        .HasForeignKey("SupersededByAttendanceID");

                    b.HasOne("GymTrackPro.Shared.Entities.User", "VoidActorUser")
                        .WithMany()
                        .HasForeignKey("VoidActorUserID");

                    b.Navigation("ActorUser");

                    b.Navigation("Member");

                    b.Navigation("SupersededByAttendance");

                    b.Navigation("VoidActorUser");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.AttendanceAdjustment", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymTrackPro.Shared.Entities.Attendance", "Attendance")
                        .WithMany("Adjustments")
                        .HasForeignKey("AttendanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTrackPro.Shared.Entities.AttendanceOperation", "Operation")
                        .WithOne("Adjustment")
                        .HasForeignKey("GymTrackPro.Shared.Entities.AttendanceAdjustment", "OperationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Attendance");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.AttendanceOperation", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymTrackPro.Shared.Entities.Attendance", "TargetAttendance")
                        .WithMany("Operations")
                        .HasForeignKey("TargetAttendanceID");

                    b.Navigation("ActorUser");

                    b.Navigation("TargetAttendance");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.AuditLog", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.MemberProjectionVersion", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.MembershipPause", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Notification", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Payment", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymTrackPro.Shared.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Subscription", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTrackPro.Shared.Entities.MembershipPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.User", b =>
                {
                    b.HasOne("GymTrackPro.Shared.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.Attendance", b =>
                {
                    b.Navigation("Adjustments");

                    b.Navigation("Operations");
                });

            modelBuilder.Entity("GymTrackPro.Shared.Entities.AttendanceOperation", b =>
                {
                    b.Navigation("Adjustment");
                });
#pragma warning restore 612, 618
        }
    }
}
